### ISSUE TITLE
Add support for Fedora 37

### ISSUE THREAD

**Issue by HrBingR** [adoptium/installer#566] opened 2022-12-17 11:03 UTC
When adding the repo to my sources I followed the CentOS/RHEL/Fedora Instructions on this page here: https://adoptium.net/installation/linux/

After adding the repo and performing a yum/dnf update I get the following error:

[anthony@fedora ~]$ sudo yum update
Adoptium                                                                                                                                                           33  B/s |  80  B     00:02    
Errors during downloading metadata for repository 'Adoptium':
  - Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/37/x86_64/repodata/repomd.xml (IP: 44.240.59.148)
Error: Failed to download metadata for repo 'Adoptium': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: Adoptium

When trying to access packages.adoptium.net via my browser, such as https://packages.adoptium.net/ui/native/rpm/, I get redirected to a JFrog login page. Signing in with my github account shows nothing and no packages, leaving me unable to do anything or download from this repo.

![image](https://user-images.githubusercontent.com/7275577/208238536-6b7c7d32-589a-4ae1-9170-102405552db4.png)
![image](https://user-images.githubusercontent.com/7275577/208238572-c125c1c8-0ceb-48ff-bcad-ae8c057a0801.png)

**Comment by gdams** [comment] 2022-12-19 10:25
Looks like we currently only support fedora 35 and 36. Adding 37 should be easy enough… I’ll take a look

**Comment by persicsb** [comment] 2023-01-16 15:03
I'd like to reopen this bug, the packages are not found:
Errors during downloading metadata for repository 'Adoptium':
  - Status code: 404 for https://packages.adoptium.net/artifactory/rpm/fedora/37/x86_64/repodata/repomd.xml (IP: 44.240.202.245)

Browsing the artifactory site, I see no Fedora 37 packages. This bug shall be reopened.

**Comment by bviktor** [comment] 2023-01-22 13:56
Yup. The Fedora 36 packages do install on F37 and a quick `java -version` check doesn't throw any errors, but I'd be better to have a proper repo for F37 :)

**Comment by zdtsw** [comment] 2023-02-09 19:22
2023.Jan release should already include the supports for F37.

**Comment by karianna** [comment] 2023-02-10 07:18
@persicsb Can you check the F37 repos?

**Comment by persicsb** [comment] 2023-02-10 12:11
> @persicsb Can you check the F37 repos?

I can verify the following:

1. The temurin-{8,11,17,19}-{jdk,jre} packages are present in the repository
2. The packages temurin-{8,11,17,19}-{jdk} packages can be installed
3. But the temurin-{8,11,17,19}-{jre} packages are not signed, thus cannot be installed. \

Please check the signing of the JRE packages.

**Comment by ascheman** [comment] 2023-02-10 16:02
Could someone (@persicsb?) open a new issue here? I think it has nothing to do with the OPs intention to get Fedora 37 support? And the state of the ticket currently makes no sense (i.e., _Waiting on OP_).

**Comment by karianna** [comment] 2023-02-11 05:09
Opened a new issue and closing this one

**Closed by karianna** 2023-02-11 05:09 UTC
Labels: Waiting on OP

**Comment by bviktor** [comment] 2023-02-13 12:29
I can confirm the new repo is present. However, I cannot confirm the packages can't be installed.
