### ISSUE TITLE
Smoke tests for MSI installer generation failed

### ISSUE THREAD

**Issue by ben-walsh** [adoptium/installer#66] opened 2019-03-12 14:15 UTC
```
Windows Installer XML Toolset Validator version 3.11.1.2318
Copyright (c) .NET Foundation and contributors. All rights reserved.

OpenJDK12-jdk_x64_windows_openj9-12.0.0.32.msi
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE02'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE03'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE04'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE05'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE06'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0217 : Error executing ICE action 'ICE07'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
smoke.exe : error SMOK0216 : An unexpected Win32 exception with error code 0x643 occurred: Action - 'ICE08' Fatal error during installation
Failed to validate MSI
Build step 'Execute Windows batch command' marked build as failure
```

They have been temporarily disabled through https://github.com/AdoptOpenJDK/openjdk-installer/pull/65.

Further investigation of why they are failing is required.

**Comment by gdams** [comment] 2019-03-12 14:17
this was caused by https://github.com/wixtoolset/issues/issues/4922. We don't build with an admin user so they were unable to install

**Comment by gdams** [comment] 2019-03-12 14:36
This PR re-enables smoke testing like we did before https://github.com/AdoptOpenJDK/openjdk-installer/pull/67

**Comment by douph1** [comment] 2019-03-13 08:35
>This PR re-enables smoke testing like we did before
We having random failure with test enable like before (without option -sval for light.exe) 
So smoke is not the problem as light get random error too

Actually there is not any validation done.
Not by light ( because of usage of -sval ) and not with smoke.exe a then end.
It is not a best practice to skip all msi validation.

We must find .. why the failure is random and enable test again within light or smoke(at then end)

First to try on another host to see if smoke work without admin user.
If YES then

Some hint to validate here : 
https://stackoverflow.com/questions/1064580/wix-3-0-throws-error-217-while-being-executed-by-continuous-integration

- PATH too long
- corrupted Windows Installer Service
- restart the Windows Installer service
- mcafee has replaced path to dll: updated the path back to c:\windows\system32\vbscript.dll

workaround to try maybe : 
- change the account used to run the service on my machine. Instead of using Network Service or Local Service I simply made the service log on with my own account which had all the necessary rights.

**Comment by douph1** [comment] 2019-03-14 09:48
I just tested on my Windows 10 machine:
Service "Windows Installer" (msiexec 5.0.17134.228)  is stopped and configured by default with "Manual starting" and "Local system" account

With user without any group provilège it works without erreur : 
light without -sval works without error
smoke works without error

**Comment by douph1** [comment] 2019-03-14 09:52
So I propose to add smoke code again and an option to disable it if needed

**Comment by douph1** [comment] 2019-03-14 20:25
smoke (msi validation) can be disabled/enabled by  PR #71 

Maybe interactif user (non admin) can access windows installer
https://sourceforge.net/p/wix/mailman/message/24361610/

If jenkins slave is executed as a service we can try do enable "interactive" on that service
or start slave agent outside of a service
https://groups.google.com/forum/#!topic/jenkinsci-users/Z7-VY1l-7hE

**Comment by aahlenst** [comment] 2020-07-05 13:10
https://github.com/AdoptOpenJDK/openjdk-installer/pull/71 was merged, [smoke testing is enabled](https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/Build.OpenJDK_generic.cmd#L264-L274). Therefore, I'm closing.

**Comment by gdams** [comment] 2020-07-06 08:37
This issue was actually about not being able to run the smoke tests on the current build agents because they are running as a non admin user.

**Comment by douph1** [comment] 2021-04-19 19:24
Wix MSI Smoke test is now used on github actions pipeline  (SKIP_MSI_VALIDATION is not set)

**Closed by douph1** 2021-04-19 19:24 UTC
Labels: bug
