### ISSUE TITLE
JAVA_HOME will not update if ever edited

### ISSUE THREAD

**Issue by nw-euronet** [adoptium/installer#418] opened 2021-12-28 19:44 UTC
I'm not sure if this is a bug or intended but we run into a problem when installing OpenJDK.

If the "JAVA_HOME" environment variable has been edited on a Windows workstation, no upgrade or installation of OpenJDK will add/edit the Java Home variable again even when you tell it to. For example: You add a JAVA_HOME env. variable and set it to "C:\java", you then delete this env. variable and restart, when you install any version of OpenJDK and choose the option to add the Java Home variable it will not do it. This also impacts upgrading OpenJDK so if someone messes with their Java Home variable, future OpenJDK updates/versions will not update the Java Home to reflect the new install path. If you install OpenJDK on a machine where nobody has messed with the JAVA_HOME env. variable, it will add Java Home just fine and when updating to a new version of openjdk, it will update the Java Home variable to reflect the new directory.

The problem is we have users who have updated their Java Home in the past and now every update of OpenJDK will break their local Java path because it holds on to the old path to OpenJDK.
Thx

Java version: Any version

Your operating system and platform: Windows 10

**Comment by karianna** [comment] 2022-01-04 10:57
Duplicate of #409

**Closed by karianna** 2022-01-04 10:57 UTC
