### ISSUE TITLE
Add support for Debian 12 (bookworm)

### ISSUE THREAD

**Issue by ReillyBrogan** [adoptium/installer#599] opened 2023-01-25 19:39 UTC
Debian started their package freeze for Bookworm on [January 12th](https://lists.debian.org/debian-devel-announce/2023/01/msg00004.html). As such now is a good time to start building packages for it and adding it to CI matrices so that Temurin packages are in a good state for the final release.

**Comment by zdtsw** [comment] 2023-02-09 19:18
I believe we have released jre for bookworm but not jdk for 2023 Jan's release, 
but the code is ready so it just need to get it out in the next release.
(unless strong opinion to re-release on jdk now)

**Comment by ReillyBrogan** [comment] 2023-02-09 21:53
JRE is fine for now. So long as the JDK packages are built during the April update we should be in good shape for the eventual Bookworm release (which is likely to fall somewhere around the middle of the year).

**Comment by zdtsw** [comment] 2023-02-10 06:51
If you are ine, we can have this issue closed.
Re-open it when needed.

**Comment by ascheman** [comment] 2023-02-15 05:44
I suggest to close this, as it is a duplicate of #585. Debian _bookworm_ was therefore already added to JDK (and JRE) by the (merged) PR #591.

**Closed** 2023-02-15 06:04 UTC
Labels: duplicate
