### ISSUE TITLE
Debian package installer instructions fail - no valid OpenPGP data found.

### ISSUE THREAD

**Issue by MarkEWaite** [adoptium/installer#436] opened 2022-02-15 03:26 UTC
## Debian package installer fails

When I follow the [Debian installation instructions](https://github.com/adoptium/website-v2/blob/main/src/asciidoc-pages/installation/linux.adoc#deb-installation-on-debian-or-ubuntu)  as linked from the installers section of the [Adoptium installation page](https://adoptium.net/installation.html?variant=openjdk11&jvmVariant=hotspot#x64_linux-jdk), the second step fails on Debian 10 ("buster") and Debian 11 ("bullseye") with the message:

```bash
$ wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | sudo apt-key add -
--2022-02-14 20:25:34--  https://packages.adoptium.net/artifactory/api/gpg/key/public
Resolving packages.adoptium.net (packages.adoptium.net)... 34.139.10.89
Connecting to packages.adoptium.net (packages.adoptium.net)|34.139.10.89|:443...
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
connected.
ERROR: The certificate of ‘packages.adoptium.net’ is not trusted.
ERROR: The certificate of ‘packages.adoptium.net’ doesn't have a known issuer.
gpg: no valid OpenPGP data found.
```

**Comment by gdams** [comment] 2022-02-15 11:16
closing as duplicate of https://github.com/adoptium/installer/issues/434

**Closed by gdams** 2022-02-15 11:16 UTC
Labels: duplicate
